### ISSUE TITLE
今天访问贵站竟然发现更新了~

### ISSUE THREAD

**Issue by dingjee** [js-fun/duyijing#10]
很感谢站长靠爱发电 自掏腰包 无广告运营着这个良心亏钱站点
有3个小问题咨询下站长：
1、您考虑做手机端样式适配 或者 出个 app吗？（我应该可以帮忙）
2、您考虑出多语言的版本吗？（英文肯定是可以的）
3、最近有些事想卜问 想写个程序模拟“大衍之数”的占卜流程 想请问下您的高见？

再次感谢您的投入与坚持~

**Comment by freizl** [comment]
> 您考虑做手机端样式适配

我觉这个比较好，我自己也没什么App应验，对于这样简单的网站，我感觉适配手机够用了。

> 您考虑出多语言的版本吗

没有想过。
要英文干嘛？
也许可以试试看。
主要要找到易经的翻译 （https://github.com/freizl/yijing）
其他就相对简单了。


> “大衍之数”的占卜流程 

曾经想过，但是我想占卜在于手动的意义更大
如果是“教学”， 告诉大家怎么用大衍之数，这到可以想想看。


欢迎一起！

**Comment by dingjee** [comment]
> 我觉这个比较好，我自己也没什么App应验，对于这样简单的网站，我感觉适配手机够用了。

手机适配确实不难，我也算半个前端，改改css完全没问题。但我对github协作还不是特别熟，这方面可能还需要您的一些指导及相互磨合，如果需要我帮忙的话~

我本科学的是交互设计，个人觉得App的功能和使用体验上都可以更加完善。但我个人近期都比较忙，如果设计整个App，可能一时半会也确实力不从心，但我个人还是希求将来能出个特别有品质的App（[check this~](https://apps.apple.com/cn/app/%E6%97%B6%E5%8E%86-%E5%8D%81%E4%BA%8C%E6%97%B6%E8%BE%B0/id1441863229?platform=iphone)）能上架Apple的AppStore或者GooglePlay，这样不仅方便而且影响面可以更广（现代版的“韦编三绝”，学易本身就是个玩味的过程，对吧？）。

> 要英文干嘛？主要要找到易经的翻译

看看这些：
[yijing.ch](https://yijing.ch/en/rollout-a-look-back/)
[ichingmastercode](https://ichingmastercode.wordpress.com/)
[IChing-TheElectronicEdition](https://www.iging.com/intro/preface.htm)

[论理雅各的《易经》英译](http://course.sdu.edu.cn/Download/4aa7af30-27d0-4518-b23b-fdc2ff7a4395.pdf)
[论 5易经 6的英译与世界传播](http://course.sdu.edu.cn/Download/f4e24e8d-1710-48f1-8960-4445fbb81102.pdf)

还有这个：

> 在二十一世纪即将来临时，我们问：《易经》在二十一世纪的发展会是怎么样？占出来的结果是“八八八七七八”，为泽地萃卦，这是六爻都不变的卦，所以答案就是萃卦的卦辞。也就是说，在二十一世纪的一百年间，《易经》学术的发展就是萃卦。萃是人文荟萃、出类拔萃，说明《易经》极有可能成为显学。首先，《易经》是中华文化的思想源头，是中国诸子百家思想最精华的部分，所以是“萃”。其次，萃卦还有精英相聚的象。自古以来，许多学术的发展都有盛衰起伏，而《易经》在二十一世纪的发展形势就非常看好。这就是答案。



> 曾经想过，但是我想占卜在于手动的意义更大

我现在用python写的一个初版 就是在用鼠标点击模拟“大衍之术”里的“分而为二以象两” 其他都程序自动化就可以了 现在问的几个 感觉结果都还行
对我个人来说 我不方便老是带着50根筮草 遇到些事情 平心静气自己就能在手机上问啊 准确性比“铜钱卦”高 何乐而不为呢

**Comment by freizl** [comment]
> 对我个人来说 我不方便老是带着50根筮草 遇到些事情 平心静气自己就能在手机上问啊 准确性比“铜钱卦”高 何乐而不为呢

我不太认同，在手机上的平心静气和实体感觉还是不一样。
但是如果你想加一个网页版的，我也是支持的。

没有筮草，也可以用数字卦么？

**Comment by freizl** [comment]
那个App确实看起漂亮。要是能做出这么一个来，还是很棒的！！

- Github issue很简单易用的，用用就会了。 
- 我们可以从手机适配开始。
- 如果能找到合适的英文翻译，可以加个英文翻译。前端需要动态切换，前端还有工作量。

**Comment by dingjee** [comment]
> 没有筮草，也可以用数字卦么？

我之前没接触过数字卦 还是从您这儿第一次看到了 我坚持“大衍之术”更多是因为传承上的绝对正统

不过如果考虑交互的话 可能确实数字卦对用户更平易些 这个问题要不就先搁置下吧 等着手App的时候再拿出来慎重考虑？

> 大衍之数五十，其用四十有九。分而为二以象两，挂一以象三，揲之以四以象四时，归奇于扐以象闰；五岁再闰，故再扐而后挂。乾之策二百一十有六，坤之策百四十有四，凡三百六十，当期之日。二篇之策，万有一千五百二十，当万物之数也。是故四营而成《易》，十有八变而成卦。——《易经·系辞传上》




> 我们可以从手机适配开始。

我手机是安卓的 我对css相对也比较有经验

但我目前的问题是 我在准备出国申请 而且是跨专业的 所以文书和补修课程的任务相对比较繁重 可能能抽出来的时间有限且都比较零碎

这个还是请您担待一下

不过好消息是 我离五十岁还很远 所以有大把时间慢慢学易😁

> 可以加个英文翻译。前端需要动态切换，前端还有工作量。

涉及大的改动的部分 个人建议先不着急 我得空会从交互方面 尝试优化下一些功能或者重新设计 我可以先出线框图（[wireframe](https://en.wikipedia.org/wiki/Website_wireframe)） 然后跟您商榷和讨论（类似建筑施工前的图纸 如果您有过跟设计部门合作的经验话 这个流程应该不会太陌生）

然后就是线框图的设计协作平台 您有指定吗 没有的话 后续我就挑个我自己顺手的了（大概率会是figma）

希望是个非常长期的项目 这样我就可以尽量多参与一些🙏



如果您近期时间比较充裕的话 可能还是您来着手网站的优化 比较现实（我可以一直参与测试及提供建议）

我这边得空就直接构思和画画App原型的线框图了 这样如何？

**Comment by freizl** [comment]
- 我会着手手机适配，但是空余时间有限，慢慢来。
- Figma蛮好的

**Comment by freizl** [comment]
Moved to
- https://github.com/js-fun/duyijing/issues/23
- https://github.com/freizl/yijing/issues/9
