### ISSUE TITLE
Support iPhone

### ISSUE THREAD

**Issue by freizl** [js-fun/duyijing#11]
1. Create a mobile friendly menu
2. Auto scale the Gua at small screen (flexbox might be good enough)
3. Think a way to deal with main page render (how to display all 64 gua in one page?)

**Comment by dingjee** [comment]
用一个类似[Boostrap的前端框架](https://getbootstrap.com/docs/5.3/layout/breakpoints/)来实现终端适配 相对会非常简单 便捷 且不容易出错

**Comment by freizl** [comment]
Bootstrap is too heavy but easy enough. The first version is using Bootstrap. I'll consider.

**Comment by freizl** [comment]
Fixed in a few commits. See from 1b1be4c8077e014ad1c570a26bb85d120d62f6a9
