### ISSUE TITLE
data.js code 代码排序

### ISSUE THREAD

**Issue by Inc0n** [js-fun/duyijing#4]
六十四卦所用的二进制代码顺序与每个卦的爻序相反，例如 “既济”，应以`101010`表示，而非`010101`。

如此改进后，更容易将六十四卦以文王卦序排列。

**Comment by freizl** [comment]
@Inc0n 你是说 0为阳 1位阴？

**Comment by Inc0n** [comment]
我原文中的意思应该是：初爻为最小位数。我当时估计是发现用这样的数序文王卦序会更容易排列。

例子：原数序
> “既济” = 101010

改进后（相反）
> “既济” = 010101

**Comment by freizl** [comment]
如果取 1为阳 0位阴 初爻在最小位， 
那么 [既济](https://zh.wikisource.org/zh-hans/%E5%91%A8%E6%98%93/%E6%97%A2%E6%BF%9F) 应该是： 010101

https://github.com/js-fun/duyijing/blob/master/app/scripts/data/data.js#L1196

**Comment by freizl** [comment]
这是我设置的八卦代码： https://github.com/js-fun/duyijing/blob/master/app/scripts/data/data.js#L1238
然后是生成64卦时，上卦在左，下卦在右。

**Comment by Inc0n** [comment]
抱歉，我采用 “既济”是一个不好的例子，再从我原先的代码翻举“屯”为例，应该可以更容易看出我的意思。

```
code = "100010",
name = "屯"
```
相比较于 https://github.com/js-fun/duyijing/blob/f3a03d5873ad96ac81831b89ea9cf97d6793d413/app/scripts/data/data_zh-cn.js#L55

然后我当时的发现是：这样的卦数序可以更容易的用文王卦序排 data.js 中的六十四卦

**Comment by freizl** [comment]
所以你把 第一位做为初爻？
怎么理解这样更容易排序文王卦序

**Comment by Inc0n** [comment]
这样就不需要从这个repo中提取data.js 👍

**Comment by Inc0n** [comment]
前人栽树，后人乘凉。造福后来学者
